export default {
  all: 'All Pokemon',
  normal: 'normal',
  fire: 'fire',
  water: 'water',
  electric: 'electric',
  grass: 'grass',
  ice: 'ice',
  ground: 'ground',
  flying: 'flying',
  ghost: 'ghost',
  rock: 'rock',
  fighting: 'fighting',
  poison: 'poison',
  psychic: 'psychic',
  bug: 'bug',
  dark: 'dark',
  steel: 'steel',
  dragon: 'dragon',
  fairy: 'fairy',
};
